[build.environment]
HUGO_VERSION = "v0.141.0"
NODE_VERSION = "v23.6.0"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = "make all"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"
